project/urls.py
from django.conf.urls.defaults import *
from django.contrib import admin
from django.contrib.admin import site

from django.views.generic import TemplateView
from apps.base.views import *

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', HomePageView.as_view(), name='home'),
    url(r'^list/town$', TownList.as_view(), name='towns'),
    url(r'^list/house$', HouseList.as_view(), name='houses'),
    url(r'^list/filter/', FilterList.as_view(), name='filter'),
    url(r'^town/(?P<slug>.+)$', TownView.as_view(), name='town_cart'),
    url(r'^house/(?P<slug>.+)$', HouseView.as_view(), name='house_cart'),
    url(r'^order$', OrderView.as_view(), name='order'),
    url(r'^contact$', ContactView.as_view(), name='contact'),


    
    # # enable the admin:
    url(r'^admin/', include(site.urls)),
)

# from django.conf import settings
# if settings.DEBUG:
#     urlpatterns += patterns(
#         '',
#         url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
#                 {'document_root': settings.MEDIA_ROOT})
#     )

project/apps/base/models.py
#-*- coding:utf-8 -*-
from django.db import models
from django.contrib import admin
from django.db.models.signals import post_save, pre_delete
from django.core.urlresolvers import reverse
from project.libs.utils import create_thumbnail, delete_thumbnail, get_thumbnail_url
from django.template import loader, Context
import os
# Create your models here.

GAS_TYPE = (
	(1, u'Есть'),
	(2, u'Нет'),
	(3, u'Можно подключить'),
)

WATER_TYPE = (
	(1, u'Скважина'),
	(2, u'Центральная'),
	(3, u'Нет')
)

WALL_TYPE = (
	(1, u'Кирпич'),
	(2, u'Пеноблок'),
)

ENTRY_TYPE = (
	(1, u'Индивидуальный'),
	(2, u'Общий')
)

class Sector(models.Model):
	title = models.CharField(max_length=255, verbose_name=u'район')

	def __unicode__(self):
		return self.title

	class Meta:
		verbose_name = u'район'
		verbose_name_plural = u'районы'




class BaseObject(models.Model):
	title = models.CharField(max_length=255, verbose_name=u'название')
	home_page = models.BooleanField(verbose_name=u"показывать на главной")
	slug = models.SlugField(verbose_name=u'системное имя', unique=True)
	price = models.PositiveIntegerField(verbose_name=u'цена')
	sector = models.ForeignKey('Sector', verbose_name=u'район')
	place = models.CharField(max_length=255, verbose_name=u'расположение')
	description = models.TextField(verbose_name=u'описание')
	gallery = models.ForeignKey('Gallery', verbose_name=u"галлерея", null=True, on_delete=models.SET_NULL)
	rate = models.PositiveIntegerField(verbose_name=u'рейтинг', default=0)

	def __unicode__(self):
		return self.title

	def get_announce(self, max_length=200):
		if len(self.description) < max_length:
			return self.description
		return self.description[:max_length] + "..."

	def get_url(self):
		return reverse(self.url_name, args=[self.slug,])

	class Meta:
		abstract = True




class BaseHouse(BaseObject):
	url_name = 'house_cart'
	inner_area = models.FloatField(verbose_name=u'площадь дома')
	area = models.FloatField(verbose_name=u'площадь участка')
	gas = models.PositiveIntegerField(choices=GAS_TYPE, verbose_name=u'газ')
	water = models.PositiveIntegerField(choices=WATER_TYPE, verbose_name=u'вода')
	wall = models.PositiveIntegerField(choices=WALL_TYPE, verbose_name=u'материал стен')

	def as_list(self):
		template = loader.get_template('base/snippets/as_list.html')
		context = Context({'object':self})
		return template.render(context)

	class Meta:
		abstract = True




class Town(BaseHouse):
	url_name = 'town_cart'
	entry = models.PositiveIntegerField(choices=ENTRY_TYPE, verbose_name=u'въезд')
	
	class Meta:
		verbose_name = u'таунхаус'
		verbose_name_plural = u'таунхаусы'




class House(BaseHouse):
	url_name = 'house_cart'

	class Meta:
		verbose_name = u'дом'
		verbose_name_plural = u'дома'




def update_filename(instance, filename):
    upload_dir = "pictures"
    return os.path.join(upload_dir, filename.lower())




class Gallery(models.Model):
	def get_main_pict(self):
		a=self.picture_set.all()
		if a:
			return a[0].picture

	class Meta:
		verbose_name = u"галлерея"
		verbose_name_plural = u"галлереи"





class Picture(models.Model):
    picture = models.ImageField(upload_to=update_filename, max_length=250)
    priority = models.PositiveIntegerField(verbose_name=u"приоритет", default=1)
    gallery = models.ForeignKey(Gallery)

    def get_url(self):
        return self.picture.url

    def get_thumb_url(self):
        return get_thumbnail_url(self.picture.url)

    def get_small_thumb_url(self):
        return get_thumbnail_url(self.picture.url, size=80)

    class Meta:
    	verbose_name = u"изображение"
    	verbose_name_plural = u"изображения"
    	ordering = ['priority',]

project/apps/base/views.py
from django.views.generic.base import TemplateView 
from django.views.generic import ListView, DetailView
from models import Town, Sector, House, BaseObject
from django.shortcuts import get_object_or_404




class MyBaseView(TemplateView):
	menu_active = 0
	def get_context_data(self, *args, **kwargs):
		context = super(MyBaseView, self).get_context_data(*args, **kwargs)
		context['t_menu_active'] = self.menu_active
		return context




class HomePageView(MyBaseView):
    template_name = "home.html"
    menu_active = 1
    
    def get_context_data(self, **kwargs):
        context = super(HomePageView, self).get_context_data(**kwargs)
        context['town_list'] = Town.objects.filter(home_page=True)[:3]
        context['sector_list'] = Sector.objects.all()
       	context['house_list'] = House.objects.filter(home_page=True)[:3]
        return context



class OrderView(MyBaseView):
	menu_active = 4
	template_name = 'order.html'



class ContactView(MyBaseView):
	menu_active = 5
	template_name = 'contact.html'


class BaseObjectListView(ListView):
	paginate_by = 200
	menu_active = 0

	def get_context_data(self, *args, **kwargs):
		context = super(BaseObjectListView, self).get_context_data(*args, **kwargs)
		context['sector_list'] = Sector.objects.all()
		context['t_menu_active'] = self.menu_active
		return context




class TownList(BaseObjectListView, ListView):
	model = Town
	template_name = "base/town_list.html"
	menu_active = 2




class BaseObjectCartView(DetailView):
	template_name = 'base/object_cart.html'




class TownView(BaseObjectCartView):
	model = Town

	def get_queryset(self):
		return Town.objects.filter(slug=self.kwargs.get('slug', ''))




class HouseView(BaseObjectCartView):
	model = House

	def get_queryset(self, *args, **kwargs):
		return House.objects.filter(slug=self.kwargs.get('slug', ''))
	



class HouseList(BaseObjectListView):
	model = House
	template_name = "base/house_list.html"
	menu_active = 3




class FilterList(BaseObjectListView):
	template_name = "base/object_list.html"
	filter_context = {}


	def get_queryset(self, *args, **kwargs):
		request = self.request.GET.copy()
		town_list = Town.objects.all()
		house_list = House.objects.all()
		context = {}

		if request.get('sector'):
			context['sector'] = int(request.get('sector'))
			town_list = town_list.filter(sector=get_object_or_404(Sector, pk=request.get('sector')))
			house_list = house_list.filter(sector=get_object_or_404(Sector, pk=request.get('sector')))
		
		if request.get('min_price'):
			context['min_price'] = request.get('min_price')
			town_list = town_list.filter(price__gte=int(request.get('min_price')))
			house_list = house_list.filter(price__gte=int(request.get('min_price')))
		
		if request.get('max_price'):
			context['max_price'] = request.get('max_price')
			town_list = town_list.filter(price__lte=int(request.get('max_price')))
			house_list = house_list.filter(price__lte=int(request.get('max_price')))

		context['type'] = request.get('type')
		self.filter_context = context

		if request.get('type') == '0':
			return town_list
		if request.get('type') == '1':
			return house_list
		return list(town_list) + list(house_list)

	def get_context_data(self, *args, **kwargs):
		context = super(FilterList, self).get_context_data(*args, **kwargs)
		context['filter'] = self.filter_context
		return context

project/templates/base.html
<!DOCTYPE html>
{% load thumbnail %}
<html lang="en">
<head>
    <title>{% block title %}Таунхаусы в Краснодаре{% endblock %}</title>
    <meta charset="utf-8">
    <link rel="stylesheet" href="{{STATIC_URL}}css/reset.css" type="text/css" media="screen">
    <link rel="stylesheet" href="{{STATIC_URL}}css/style.css" type="text/css" media="screen">
    <link rel="stylesheet" href="{{STATIC_URL}}css/grid.css" type="text/css" media="screen"> 
    <link rel="stylesheet" href="{{STATIC_URL}}bootstrap/css/bootstrap.min.css" type="text/css" media="screen">
    <link rel="stylesheet" href="{{STATIC_URL}}bootstrap/css/bootstrap-select.min.css" type="text/css" media="screen">


    <script src="{{STATIC_URL}}js/jquery-1.6.3.min.js" type="text/javascript"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
    <script src="{{STATIC_URL}}bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
    <script src="{{STATIC_URL}}bootstrap/js/bootstrap-select.min.js" type="text/javascript"></script>

   	<!--[if lt IE 8]>
    <div style=' clear: both; text-align:center; position: relative;'>
        <a href="http://windows.microsoft.com/en-US/internet-explorer/products/ie/home?ocid=ie6_countdown_bannercode">
        	<img src="http://storage.ie6countdown.com/assets/100/images/banners/warning_bar_0000_us.jpg" border="0" height="42" width="820" alt="You are using an outdated browser. For a faster, safer browsing experience, upgrade for free today." />
        </a>
    </div>
	<![endif]-->
    <!--[if lt IE 9]>
   		<script type="text/javascript" src="js/html5.js"></script>
        <link rel="stylesheet" href="css/ie.css" type="text/css" media="screen">
	<![endif]-->
    <script type="text/javascript">
        $(function(){
            $('.selectpicker').selectpicker();
        })
    </script>
    {% block head%}{% endblock %}
</head>
<body id="page1">
	<!--==============================header=================================-->
    <header>
    	<div class="menu-row">
        	<div class="main">
            	<nav class="wrapper">
                    {% block top_menu %}
                    <ul class="menu">
                        <li><a {%ifequal t_menu_active 1%}class="active"{%endifequal%} href="{% url home %}">Главная</a></li>
                        <li><a {%ifequal t_menu_active 2%}class="active"{%endifequal%} href="{% url towns %}">Таунхаусы</a></li>
                        <li><a {%ifequal t_menu_active 3%}class="active"{%endifequal%} href="{% url houses %}">Дома</a></li>
                       <!--  <li><a {%ifequal t_menu_active 4%}class="active"{%endifequal%} href="{% url order %}">Под заказ</a></li> -->
                        <li><a {%ifequal t_menu_active 5%}class="active"{%endifequal%} href="{% url contact %}">Контакты</a></li>
                    </ul>
                    {% endblock %}
                </nav>
            </div>
        </div>
        {% block extended_header %}{% endblock %}
    </header>
    <div id="content">
        <div class="main">
            <div class="container_12">
                <div class="wrapper">
                    {% block content %}{% endblock %}                       
                </div>
            </div>
        </div>
    </div>
    
	<!--==============================footer=================================-->
    <footer>
        <div class="main">
        	<div class="aligncenter">
                {% block footer %}{% endblock %}    
            </div>
        </div>
    </footer>
    {% block bottom_js %}{% endblock %}
    <!-- Yandex.Metrika counter -->
    <script type="text/javascript">
    (function (d, w, c) {
        (w[c] = w[c] || []).push(function() {
            try {
                w.yaCounter22310387 = new Ya.Metrika({id:22310387,
                        clickmap:true,
                        trackLinks:true,
                        accurateTrackBounce:true});
            } catch(e) { }
        });

        var n = d.getElementsByTagName("script")[0],
            s = d.createElement("script"),
            f = function () { n.parentNode.insertBefore(s, n); };
        s.type = "text/javascript";
        s.async = true;
        s.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//mc.yandex.ru/metrika/watch.js";

        if (w.opera == "[object Opera]") {
            d.addEventListener("DOMContentLoaded", f, false);
        } else { f(); }
    })(document, window, "yandex_metrika_callbacks");
    </script>
    <noscript><div><img src="//mc.yandex.ru/watch/22310387" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
    <!-- /Yandex.Metrika counter -->
</body>
</html>

project/templates/base/house_list.html
{% extends "base/object_list.html" %}

project/templates/base/object_cart.html
{% extends "base.html" %}
{% load thumbnail %}
{% block title %}{{ object.title }}{% endblock %}
{% block content %}
	<div class="well">
		<fieldset>
			<legend>{{ object.title }}</legend>
			{% thumbnail object.gallery.get_main_pict "920" as image %}
			<img src="{{ image.url }}"/>
			{% endthumbnail %}
			<p>{{ object.description }}</p>
		</fieldset>
	</div>
{% endblock %}

project/templates/base/object_list.html
{% extends "base.html" %}
{% block title %}Список объектов{% endblock %}
{% load url from future %}

{% block content %}
	{% include "filter_snippet.html" %}
	{% block list_content %}
	{% for object in object_list %}
        {{ object.as_list }}
    {% endfor %}
    {% endblock %}

{% endblock %}

project/templates/base/snippets/as_list.html
{% load thumbnail %}
<div class="list-object well">
    <div class="picture">
    	<a href="{{ object.get_url }}">
    		{% thumbnail object.gallery.get_main_pict.path "300" as im %}
    			<img src="{{ im.url }}"/>
    		{% empty %}
    			<p>No image</p>	
    		{% endthumbnail %}
    	</a>
    </div>
    <div class="description">
        <h3><a href="{{object.get_url}}">{{ object.title }}</a></h3>
        <div class="text">
            {{ object.get_announce }}
        </div>
        <div class="properties">
            <ul>
                <li><span>Район:</span> {{object.sector}}</li>
                <li><span>Площадь:</span> {{object.inner_area}} м2</li>
                <li><span>Участок:</span> {{object.area}} сот.</li>
                <li><span>Газ:</span>{{object.get_gas_display}}</li>
            </ul>
            <span class="price">{{object.price}} т.р.</span>                                    
        </div>
        <div class="clearfix"></div>
    </div>
</div>

project/templates/base/town_list.html
{% extends "base/object_list.html" %}

project/templates/contact.html
{% extends "base.html" %}
{% block content %}
<div class="well">
	<fieldset>
		<legend>Как с нами связаться</legend>
		<div class="row">
			<div class="span4">
				<img src="{{STATIC_URL}}images/contact.png" class="pull-left" />
				<div class="clr"></div>
				<br><br>
				<p>
					Так же вы можете связаться с нами по телефонам:<br>
					<strong class="pull-right">8(918)0156-186</strong><br>
					<strong class="pull-right">8(962)8690-448</strong>
				</p>
			</div>
			<div class="span6">
			<h3>Закажи звонок специалиста!</h3>
				<form id="contact-form" method="post" enctype="multipart/form-data">                    
					<fieldset class="span5">
						<label><span class="text-form">Ваше имя:</span><input type="text"></label>
						<label><span class="text-form">Ваш телефон:</span><input type="text"></label>      
						<button class="btn btn-success btn-large pull-right">Заказать</button>
					</fieldset>						
				</form>
			</div>
		</div>
	</fieldset>
</div>
{% endblock %}

project/templates/filter_snippet.html
{% load url from future %}
<div class="well">
		<form action="{% url 'filter' %}" method="GET" id="filter">
			<script type="text/javascript">
				$('#filter').submit(function() {
					$('#type-input').attr('value', $('#filter-type .active').index());
				  return true;
				});
			</script>
		    <div class="span2">
		        <label>Выберите район</label>
		        <select class="selectpicker span2" name="sector">
		        	<option value="">Все</option>
		            {% for sector in sector_list %}
		            	<option value="{{sector.pk}}" {% if sector.pk == filter.sector %} selected="selected" {% endif %}>{{sector}}</option>
					{% endfor %}
		        </select>
		    </div>
		    <div class="span4">
		        <label>Выберите тип объекта</label>
		        <div class="btn-group" id="filter-type" data-toggle="buttons-radio">
		          <button type="button" class="btn{% if filter.type == '0' %} active{% endif %}">Таунхаус</button>
		          <button type="button" class="btn{% if filter.type == '1' %} active{% endif %}">Дом</button>
		          <button type="button" class="btn{% if filter.type == '2' %} active{% endif %}">Дуплекс</button>
		          <button type="button" class="btn{% if filter.type == '3' %} active{% endif %}">Участок</button>
		        </div>
		        <input type="hidden" name='type' id="type-input" />
		    </div>
		    <div class="span2">
		        <label>Цена от:</label>
		        <select class="selectpicker span2" name="min_price">
		            <option value="">&nbsp;</option>
		            <option {% if filter.min_price == '1000' %}selected="selected"{% endif %}>1000</option>
		            <option {% if filter.min_price == '2000' %}selected="selected"{% endif %}>2000</option>
		        </select>
		    </div>
		    <div class="span2">
		        <label>Цена до:</label>
		        <select class="selectpicker span2" name="max_price">
		            <option value="">&nbsp;</option>
		            <option {% if filter.max_price == '1000' %}selected="selected"{% endif %}>1000</option>
		            <option {% if filter.max_price == '2000' %}selected="selected"{% endif %}>2000</option>
		        </select>
		    </div>
		    <div class="pull-right">
		        <label>&nbsp;</label>
		        <button class="btn btn-success">Подобрать</button>
		    </div>
	    </form>
	    <div class="clearfix"></div>
	</div>

project/templates/home.html
{% extends "base.html" %}
{% load thumbnail %}
{% block extended_header %}
        <div class="row-bot">
            <div class="row-bot-bg">
                <div class="main">
                    <div class="slider-wrapper">
                        {% for town in town_list %}
                        <div class="slide active">
                            <div class="picture">
                                {% thumbnail town.gallery.get_main_pict "400x347" crop="center" as image %}
                                    <img src="{{image.url}}" />
                                {% endthumbnail %}
                            </div>                        
                            <div class="desc">
                                <h2>{{town.title}}</h2>
                                <p>{{town.get_announce}}</p>
                                <a href="#" class="btn btn-success btn-large pull-right">Узнай подробнее</a>
                            </div>
                        </div>
                        {% endfor %}
                        <div class="slide">
                            <div class="picture">
                                <img src="{{STATIC_URL}}images/1.jpg" width="400" height="347" />
                            </div>                        
                            <div class="desc">
                                <h2>Дом милый дas fas fs ом</h2>
                                <p>
                                    Таунхаусы расположены таким образом, что каждый владелец апартаментов в таунхаусе (не более 2 на один таунхаусfsa fasdf sadf sf s) имеет собственную площадку — участок не менее 2 соток для отдыха и цветочных газонов перед входом в собственный дом. Здесь можно поставить шезлонги и устроить пикник прямо под окнами своего дома.
                                </p>
                                <a href="#" class="btn btn-success btn-large pull-right">Узнай подробнее</a>
                            </div>
                        </div>
                    </div>
                    <div class="wrapper">
                        <div class="img-indent2"><img src="{{STATIC_URL}}images/gift.png" alt=""></div>
                        <div class="extra-wrap">
                            <div class="text-1">
                                <span class="gift-title">Ваша скидка ждёт Вас!</span>

                                Заказав звонок через сайт, вы получаете скидку 5 000 р. Для того что бы заказать звонок вы можете заполнить форму в разделе контакты, или нажать кнопку "Заказать звонок" под любым объектом. Скидка действует на все объекты.
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
{% endblock %}

{% block content %}
    
    {% include "filter_snippet.html" %}
    <div class="list-objects-wrapper">
    {% if town_list %}
        <h2>Таунхаусы в Краснодаре</h2>
        {% for object in town_list %}
            {{object.as_list}}
        {% endfor %}
        <a href="{% url towns %}" class="btn btn-large btn-success pull-right">Посмотреть все</a>
        <div class="clearfix"></div>
        </div>
    {% endif %}
    {% if house_list %}
        <h2>Дома в Краснодаре</h2>
        {% for object in house_list %}
            {{ object.as_list }}
        {% endfor %}
        <a href="{% url houses %}" class="btn btn-large btn-success pull-right">Посмотреть все</a>
    {% endif %}
    </div>

    
        
{% endblock %}

{% block bottom_js %}
 <script type="text/javascript">
        $(function(){
            setInterval(function(){
                var Slides = $('.slider-wrapper .slide');
                var current = $('.slider-wrapper .slide.active').index();
                var next = -1;
                if (current >= (Slides.length - 1)){
                    next = 0;
                } else {
                    next = current + 1;
                }

                $(Slides[current]).animate(
                {
                    'opacity': 0,
                }, 
                500, 
                function() {
                    $(Slides[current]).removeClass('active');
                    $(Slides[next]).attr('style','opacity:0').addClass('active');
                    $(Slides[next]).animate(
                    {
                       'opacity': 1,
                    },
                    1000
                    );
                })
            }, 12000);
        });
    </script>
{% endblock %}

project/templates/order.html
{% extends "base.html" %}
{% block content %}
<div class="well">
	<fieldset>
		<legend>Строим дома под заказ</legend>
		<p>
			sdklsa asdfkj
		</p>
	</fieldset>
</div>
{% endblock %}